steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/launchedberry/gmail-finance-manager/app:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/launchedberry/gmail-finance-manager/app:latest'

images:
  - 'us-central1-docker.pkg.dev/launchedberry/gmail-finance-manager/app:latest'

    options:
      logging: CLOUD_LOGGING_ONLY
