steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - '[YOUR_REGION]-docker.pkg.dev/[YOUR_PROJECT_ID]/gmail-finance-manager/app:latest'
      - '.'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - '[YOUR_REGION]-docker.pkg.dev/[YOUR_PROJECT_ID]/gmail-finance-manager/app:latest'

# Specify the image to be used by the Cloud Run deployment
images:
  - '[YOUR_REGION]-docker.pkg.dev/[YOUR_PROJECT_ID]/gmail-finance-manager/app:latest'

# --- MISSION-CRITICAL LOGGING FIX ---
# This option resolves the error by sending logs directly to Cloud Logging.
options:
  logging: CLOUD_LOGGING_ONLY